### PR TITLE
Snap to picture after scrolling

### PR DESCRIPTION
**Pull request by mrooding**
I noticed 2 problems when simply swiping across the `ScrollView`:

- The buttons do not get updated
- The component did not snap to a certain picture

I've implemented a snap to image which snaps to the picture which occupies the most space in the slider. By calling the `_move` method after the user stops swiping the picture snapping works and the buttons get updated correctly

### CODE REVIEW

**Comment by PaulBGD** [comment]
I'd prefer you write the debounce method yourself, as I'd like to keep this library to 0 dependencies.

**Comment by mrooding** [comment]
I updated the PR to use a custom debounce method

**Comment by PaulBGD** [comment]
Just want to say I appreciate the PRs, I've just been very busy lately. I'll try to get around to reviewing them by the end of the week.

**Comment by indesignlatam** [comment]
@mrooding I just tried your method and works great. We don't need to use PanResponder or anything to make it work correctly on iOS and android with your method.

**Comment by pcooney10** [comment]
👍 this PR worked for me as well

**Comment by ArtiomShapovalov** [comment]
Fixed in #53

**Pull request closed without merging**
