### PR TITLE
Support slider loop

### PR DESCRIPTION
**Pull request by lizouzt**
Let gallery support picture loop

### CODE REVIEW

**Comment by PaulBGD** [comment]
You removed support for older versions of React Native, which I plan on still supporting.

**Comment by lizouzt** [comment]
Sorry for that.I just use with version:45 before.
let me add it back.

**Comment by PaulBGD** [comment]
Thanks! I'm going to get around to this ASAP.

**Comment by ArtiomShapovalov** [comment]
Implemented in #53

**Pull request closed without merging**
