### PR TITLE
Add onPress image and backgroundColor options

### PR DESCRIPTION
**Pull request by superandrew213**
I needed these options for a project. Let me know if you want me to change anything.

### CODE REVIEW

**Comment by PaulBGD** [comment]
Instead of passing backgroundColor as a prop, I'd rather have you just pass a styles object. Ex:
```
<Animated.View styles={[ourStyles, this.props.styles]} ..
```

**Comment by superandrew213** [comment]
Sure, will update that.

**Comment by PaulBGD** [comment]
I'll merge this now, but it'll be a day or two before I publish a new release.

**Comment by superandrew213** [comment]
Sure, no problem

**Pull request merged**
