### PR TITLE
fix android not updating the indicators

### PR DESCRIPTION
**Pull request by dready**
because onPanResponderRelease/Terminate is not called within a ScrollView, you need a View for that.

Also you need to add onPanResponderTerminate, onStartShouldSetPanResponder, onMoveShouldSetPanResponder.

### CODE REVIEW

**Comment by PaulBGD** [comment]
I'll try to check this out by the end of the week.

**Comment by somoso** [comment]
How is the progress with this pull request?

**Comment by matheusrocha89** [comment]
I tested this PR it works fine on Android, but breaks on iOS

**Comment by ArtiomShapovalov** [comment]
Fixed in #53

**Pull request closed without merging**
