### PR TITLE
FlexGrow fix

### PR DESCRIPTION
**Pull request by cjoelrun**
Implicit flexBasis: 0 now being correctly treated. Removing the bad flex: 1 style or changing it to flexGrow: 1 should solve most if not all layout issues your see

https://github.com/facebook/react-native/issues/11481

### CODE REVIEW

**Comment by PaulBGD** [comment]
There's a PR for this already, #27 
I asked on there what we would have to do for backwards compatibility, does keeping `flex: 1` work for that? Or do we have to do version detection?

**Comment by aranda-adapptor** [comment]
@PaulBGD I tried applying the the changes in this PR but it did resolve the error I am seeing in RN 0.42.0: `View was rendered with explicitly set width/height but with a 0 flexBasis. (This might be fixed by changing flex: to flexGrow:)`.

I also tried keeping `flex: 1`, which helped, but the error still occurred depending on the style properties of the container components.

I then tried adding both `flex: 1` and `flexGrow: 1` to your `container` style. I didn't see the error after that, but I'm still getting layout issues with the round buttons being rendered way below the actual images.

Have you had a chance to test the component with the latest RN?

screen shot 2017-03-28 at 5 44 30 pm

**Comment by PaulBGD** [comment]
I have not, as I'm only using this in a production app built on .19 (cannot be updated due to https://github.com/facebook/react-native/issues/4968) so I haven't had a reason to update it. I'll try to go through all the open things on this project soon.

**Comment by ArtiomShapovalov** [comment]
Fixed in #53

**Pull request closed without merging**
