### PR TITLE
Improve pan responder which fixes bug that shows up in release build

### PR DESCRIPTION
**Pull request by superandrew213**

### CODE REVIEW

**Comment by PaulBGD** [comment]
You need to rebase on master before I can pull this.

**Comment by superandrew213** [comment]
Sorry my bad. Done

**Comment by superandrew213** [comment]
@PaulBGD can you take this in or is there anything else you want me to change?

**Comment by PaulBGD** [comment]
I just need to get around to testing it, I should get that done by tomorrow.

**Comment by PaulBGD** [comment]
Sorry for taking so long to get around to this. Looks great.

**Pull request merged**
