### PR TITLE
Autoplay, loop, custom buttons, example app and other changes.

### PR DESCRIPTION
**Pull request by ArtiomShapovalov**
Add new features. Also, add flow.js and clean up the code a little bit.

### CODE REVIEW

**Comment by PaulBGD** [comment]
This looks great, but is it backwards compatible with apps using this library already? What work would need to be put into that?

**Comment by ArtiomShapovalov** [comment]
In this pull request, I remove height prop and move this functionality into style={height: ...} instead. Other than that it is compatible, you only need to move height prop into style object, in case you need static height on the slider for some reason.

**Comment by ArtiomShapovalov** [comment]
With the last commit, you basically have an option to render anything inside slider. I add `customSlide` prop because when an image is loading we need to add an activity indicator to the background of the image or something else. There are an infinite amount of options how a developer can handle image rendering, so I decided to add a prop to let him customize slide component anyway he wants.

**Comment by ArtiomShapovalov** [comment]
Changes in this pull request address issues #52, #44, #41, #29, #26, #30.
I do not check Android issues yet, my focus is on iOS primarely, but I will investigate soon.

**Comment by ArtiomShapovalov** [comment]
In the last commit, I tried to add Android support and have partially succeeded. It works now and addresses issue #20. 

But I could not figure out how to implement loop on both sides on android because of difference in ScrollView behavior.

**Comment by PaulBGD** [comment]
Thank you for putting the work in. I'll add you to the project so you can merge this PR.

**Pull request merged**
